In [25]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

In [27]:

students_details=pd.read_csv("results.csv")
students_details

    id  subject1  subject2 Pass
0    0        32        50  yes
1    1        10        42   no
2    2        40        45  yes
3    3        55        10   no
4    4        35        50  yes
..  ..       ...       ...  ...
95  95        47        24   no
96  96        40        41  yes
97  97        14        33   no
98  98        43        56  yes
99  99        54        16   no

[100 rows x 4 columns]

In [5]:
sub1=students_details.loc[1:50,"subject1"]
x1=np.array(sub1)
x1

array([10, 40, 55, 35, 25, 32, 50, 35, 42, 39, 20, 10, 45, 45, 49, 12, 49,
       50, 30, 15, 19, 48, 45, 36, 18, 42, 51, 33, 22, 31, 52, 37, 44, 41,
       21, 14, 47, 46, 48, 11, 50, 51, 29, 16, 18, 47, 46, 38, 15, 43])

In [6]:
sub2=students_details.loc[1:50,"subject2"]
x2=np.array(sub2)
x2

array([42, 45, 10, 50, 20, 30, 50, 35, 60, 30, 30, 50, 10, 45, 30, 50, 49,
       49, 22, 35, 43, 12, 25, 48, 33, 55, 12, 47, 25, 34, 51, 39, 58, 28,
       29, 48, 15, 46, 32, 52, 50, 48, 24, 36, 44, 14, 26, 42, 31, 53])

In [7]:
add=x1+x2
total=np.array(add)
total

array([ 52,  85,  65,  85,  45,  62, 100,  70, 102,  69,  50,  60,  55,
        90,  79,  62,  98,  99,  52,  50,  62,  60,  70,  84,  51,  97,
        63,  80,  47,  65, 103,  76, 102,  69,  50,  62,  62,  92,  80,
        63, 100,  99,  53,  52,  62,  61,  72,  80,  46,  96])

In [8]:
X=np.array(total).reshape(-1,1)
X

array([[ 52],
       [ 85],
       [ 65],
       [ 85],
       [ 45],
       [ 62],
       [100],
       [ 70],
       [102],
       [ 69],
       [ 50],
       [ 60],
       [ 55],
       [ 90],
       [ 79],
       [ 62],
       [ 98],
       [ 99],
       [ 52],
       [ 50],
       [ 62],
       [ 60],
       [ 70],
       [ 84],
       [ 51],
       [ 97],
       [ 63],
       [ 80],
       [ 47],
       [ 65],
       [103],
       [ 76],
       [102],
       [ 69],
       [ 50],
       [ 62],
       [ 62],
       [ 92],
       [ 80],
       [ 63],
       [100],
       [ 99],
       [ 53],
       [ 52],
       [ 62],
       [ 61],
       [ 72],
       [ 80],
       [ 46],
       [ 96]])

In [9]:
y_text=students_details.loc[1:50,"Pass"]
y_text

1      no
2     yes
3      no
4     yes
5      no
6      no
7     yes
8     yes
9     yes
10     no
11     no
12     no
13     no
14    yes
15     no
16     no
17    yes
18    yes
19     no
20     no
21     no
22     no
23     no
24    yes
25     no
26    yes
27     no
28    yes
29     no
30     no
31    yes
32    yes
33    yes
34     no
35     no
36     no
37     no
38    yes
39     no
40     no
41    yes
42    yes
43     no
44     no
45     no
46     no
47     no
48    yes
49     no
50    yes
Name: Pass, dtype: object

In [11]:
le = LabelEncoder()
y = le.fit_transform(y_text)
y

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1])

In [12]:
model = GaussianNB()
model.fit(X, y)

GaussianNB()

In [14]:
mark=int(input("Enter your subject mark:"))
test_mark=np.array(mark).reshape(-1,1)
test_mark
ans=model.predict(test_mark)
print(ans)
print(le.inverse_transform(ans))

Enter your subject mark:85
[1]
['yes']

In [15]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import LabelEncoder

In [16]:
data=pd.read_csv("food.csv")
data

   Customer  Spicy  Cheese Likes Food
0        C1      1       0        Yes
1        C2      0       1        Yes
2        C3      1       1        Yes
3        C4      0       0         No
4        C5      1       0        Yes
..      ...    ...     ...        ...
95      C96      0       0         No
96      C97      1       0        Yes
97      C98      0       1        Yes
98      C99      1       1        Yes
99     C100      0       0         No

[100 rows x 4 columns]

In [17]:
S=data["Spicy"]
C=data["Cheese"]
X=np.column_stack((S,C))
X

array([[1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0]])

In [19]:
y_text=data["Likes Food"]
y_text

0     Yes
1     Yes
2     Yes
3      No
4     Yes
     ...
95     No
96    Yes
97    Yes
98    Yes
99     No
Name: Likes Food, Length: 100, dtype: object

In [20]:
le = LabelEncoder()
y = le.fit_transform(y_text)
y

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [21]:
model = BernoulliNB()
model.fit(X, y)

BernoulliNB()

In [28]:
spicy_food=int(input("Enter Your Answer(1-yes,no-0):"))
cheese_food=int(input("Enter Your Answer(1-yes,no-0):"))
test_food=np.array([spicy_food,cheese_food]).reshape(1,-1)
test_food
answer=model.predict(test_food)
print(answer)
print(le.inverse_transform(answer))

Enter Your Answer(1-yes,no-0):1
Enter Your Answer(1-yes,no-0):0
[1]
['Yes']